version: "3.9"
services:
  micro-root:
    build: ./root-config
    image: micro-root
    ports:
      - "9000:80"
  micro-angular:
    build: ./angular-app
    image: micro-angular
    ports:
      - "4200:80"
  micro-react:
    build: ./react-app
    image: micro-react
    ports:
      - "8080:80"
  micro-vue:
    build: ./vue
    image: micro-vue
    ports:
      - "5004:80"
